files = [
    "instance_4_1.pddl",
    "instance_4_2.pddl",
    "instance_4_3.pddl",
    "instance_5_1.pddl",
    "instance_5_2.pddl",
    "instance_5_3.pddl",
    "instance_6_1.pddl",
    "instance_6_2.pddl",
    "instance_6_3.pddl",
    "instance_7_1.pddl",
    "instance_7_2.pddl",
    "instance_7_3.pddl",
    "instance_8_1.pddl",
    "instance_8_2.pddl",
    "instance_8_3.pddl",
    "instance_9_1.pddl",
    "instance_9_2.pddl",
    "instance_9_3.pddl",
    "instance_10_1.pddl",
    "instance_10_2.pddl",
    "instance_10_3.pddl",
    "instance_11_1.pddl",
    "instance_11_2.pddl",
    "instance_11_3.pddl",
    "instance_12_1.pddl",
    "instance_12_2.pddl",
    "instance_12_3.pddl",
    "instance_13_1.pddl",
    "instance_13_2.pddl",
    "instance_13_3.pddl",
    "instance_14_1.pddl",
    "instance_14_2.pddl",
    "instance_14_3.pddl",
    "instance_15_1.pddl",
    "instance_15_2.pddl",
    "instance_15_3.pddl",
    "instance_16_1.pddl",
    "instance_16_2.pddl",
    "instance_16_3.pddl",
    "instance_17_1.pddl",
    "instance_17_2.pddl",
    "instance_17_3.pddl",
    "instance_18_1.pddl",
    "instance_18_2.pddl",
    "instance_18_3.pddl",
    "instance_19_1.pddl",
    "instance_19_2.pddl",
    "instance_19_3.pddl",
    "instance_20_1.pddl",
    "instance_20_2.pddl",
    "instance_20_3.pddl",
]

path = "/home/afavier/CAI/NumericTCORE/benchmark/plant-watering-nc/"

for i,file in enumerate(files):
    with open(path+file, 'r') as f:
        content = f.read()
    with open(path+"new/"+f"pfile{i}.pddl", 'w') as f:
        f.write(content)